### ISSUE TITLE
Implement Notifications model

### ISSUE THREAD

**Issue by regisb** [edly-io/forum#15]

**Comment by Faraz32123** [comment]
Closing this Issue as
Notifications model/APIs in ruby is not being used by edx-platform via discussion mfe.
Only inline notification appears (as shown in below picture) with number of unread_comments_count which is calculated on the basis of last_activity_at field.
![Screenshot 2024-08-08 at 12 41 40 PM](https://github.com/user-attachments/assets/9c328214-e7ed-427e-a23a-97fb2e515acd)

If we see files at_user_observer.rb , post_reply_observer.rb, post_topic_observer.rb, it creates notifications (seems like signals). But these observers are commented out in app.rb on line 92 to 95 saying Comment out observers until notifications are actually set up properly...
