### ISSUE TITLE
Implement a mechanism in edx-platform to duplicate GET requests and send them both to v1 and v2

### ISSUE THREAD

**Issue by regisb** [edly-io/forum#4]
Past experience with the Ruby unit tests indicates that test coverage is not sufficient to give us great confidence about the reliability of the v2 implementation. Thus, we propose to add an extra layer of confidence by testing the v2 API GET endpoints in production. This will be done by sending GET requests both to the v1 and the v2 backends:

```
response1 = client.get(“http://forum/api/” + endpoint, params=params)
response2 = client.get(“http://forumv2/api/” + endpoint, params=params) # "forumv2" is actually "localhost:8000"
if response2 != response1:
    logging.error(f“Forum v2 diff for endpoint {endpoint} with params={params}. Expected: {response1}. Got: {response2}.”)
return response1
```

Our goal will be to remove all such errors. Because GET requests are idempotent, and most of the complexity of the v1 API comes from GET endpoints, this approach will considerably improve our confidence in the new v2 implementation.

Running duplicate queries will undoubtedly cause slowdowns. If these slowdowns are unacceptable, then we will duplicate queries for a randomized subsample of all requests.

**Comment by taimoor-ahmed-1** [comment]
https://gist.github.com/taimoor-ahmed-1/9e947a06d127498a328475877e41d7c0
https://github.com/edly-io/edx-platform/pull/571/files
