### ISSUE TITLE
Change settings names to be unambiguous when configuring the LMS

### ISSUE THREAD

**Issue by ormsbee** [edly-io/forum#45]
The settings for this app are currently:

https://github.com/edly-io/forum/blob/012ed740ffebb01cde11ec49e159708b62c18f9a/forum/settings/common.py#L13-L15

In the context of just this app, those values are unambiguous. But in the context of writing configuration files for the LMS as a whole, those settings names are confusing, since ModuleStore also uses MongoDB.

Please either rename the settings to make it clear that it's being scoped to the forums app (e.g. `FORUMS_MONGO_HOST`), or make a top level settings dictionary for this app to put key+values in (e.g. `FORUMS['MONGO_HOST']`).

**Comment by taimoor-ahmed-1** [comment]
https://github.com/edly-io/forum/pull/55

**Comment by regisb** [comment]
This issue is addressed by #55. But I see one issue: when `MONGO_HOST` changes in edx-platform, `FORUM_MONGO_HOST` is not going to change in a consistent way. To address this, we should default `FORUM_MONGO_HOST` to `MONGO_HOST` (likewise for all PORT, etc. settings).

**Comment by regisb** [comment]
Closed by #93; in the forum app, the mongodb connection is configured via two settings: `FORUM_MONGODB_DATABASE` and `FORUM_MONGODB_CLIENT_PARAMETERS`.
