### ISSUE TITLE
On a live instance of Open edX, make sure that all calls go to v2 (and are consistent with v1 responses)

### ISSUE THREAD

**Issue by regisb** [edly-io/forum#47]
Once all views have been migrated, we should verify that no calls to v2 are transferred to v1. We can achieve that by logging an error each time a request is forwarded from v2 to v1.

In addition, we should verify that GET requests are consistent with v1 responses; we can do that thanks to #4.

Testing should be performed manually on an actual (test) instance of Open edX, covering all possible use cases.

**Comment by Faraz32123** [comment]
- response of get thread API varies when thread type is question and it was varying according to query params.
- response of get thread API varies when thread type is question and we endorse and un-endorse it.
- response for user's subscribed threads was also different as it wasn't deleting subscriptions of the threads on deleting the thread.

Will make a PR for above v1/v2 differences.
