### ISSUE TITLE
Migrate from HTTP to native Python API in edx-platform

### ISSUE THREAD

**Issue by regisb** [edly-io/forum#49]
Currently, edx-platform interacts with Forum v2 via an HTTP (REST) API. But this protocol is no longer appropriate once the forum application is in the same Python runtime as edx-platform. Thus, forum v2 must expose a native Python API and calls to the forum HTTP client must be replaced. This means that in edx-platform, all calls to `openedx.core.djangoapps.django_comment_common.comment_client.utils.perform_request` must be replaced by a call to a corresponding `forum.api.xxx` function. 

Forum v2 tests must also be migrated to accomodate for the new API.

**Comment by regisb** [comment]
See upstream PR: https://github.com/openedx/edx-platform/pull/35490

**Comment by regisb** [comment]
Am I correct in understanding that all that remains to close this issue is to convert the edx-platform unit tests?

**Comment by Faraz32123** [comment]
> Am I correct in understanding that all that remains to close this issue is to convert the edx-platform unit tests?

yes, we can also create a new issue for that and close this one?

**Comment by regisb** [comment]
Yes, please do that.

**Comment by Faraz32123** [comment]
closing this issue in favor of this working [PR](https://github.com/openedx/edx-platform/pull/35671/) in edx-platform as Native python APIs have been created and migrated in edx-platform.
