### ISSUE TITLE
Create ERD for forum v2

### ISSUE THREAD

**Issue by taimoor-ahmed-1** [edly-io/forum#85]
We need to create an ERD for forum v2 mysql based models before juming into implementation. This will also serve as documentation of our new models.

**Comment by taimoor-ahmed-1** [comment]
![Image](https://github.com/user-attachments/assets/5e1e2774-92df-4fbe-8a69-cf3f02313456)

**Comment by Faraz32123** [comment]
> ![Image](https://private-user-images.githubusercontent.com/68893403/366320803-5e1e2774-92df-4fbe-8a69-cf3f02313456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzU2MzIsIm5iZiI6MTcyNjAzNTMzMiwicGF0aCI6Ii82ODg5MzQwMy8zNjYzMjA4MDMtNWUxZTI3NzQtOTJkZi00ZmJlLThhNjktY2YzZjAyMzEzNDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA2MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYTAzZmQwMjBmN2Y4NmUxNDNlNWU5NjVkZTVjODEyMGVkMjUwMzExNDE3ZDNmODNmMjllY2IxY2ZiMmVmODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jPhyDYthfkyfYN_hwbqLcW5tSRa-RhsPV0Tdnq90oWU)

- I think we can have single model of `Content` instead of having 3 models including `Comment` and `CommentThread`. We can skip `Comment` and `CommentThread` and save the data directly in `Content` model based on it's 2 types that can be `comment or thread`.
- we can remove `Activity` model, i think. We wrote in our decisions doc that it's not being used. Do we have still usage for this model?
- Hmmm, we can also remove `LastReadTime` table and adjust/manage a single field of `last_read_time` in `ReadState` model.
- Do we have some usage for `Position` table in our current implementation? or We can adjust it's single field `position` if require, in some other model.

I think we can have a joined meet/call to finalize the structure...

**Comment by regisb** [comment]
1. User.default_sort_key, Position.content_type, Edit.reason_code, etc. should be enums (I think).
2. Timestamp fields should instead be localized datetimes.
3. Do we need CommentThread._type? According to [the docs](https://github.com/edly-io/forum/blob/master/docs/references/v1_models.rst#commentthread) it should always be "CommentThread".
4. Do we need Comment.course_id, given that it's already present in CommentThread.course_id?
5. Rename Activity.happend_at to Activity.happened_at.
6. Do we really need to store Vote.point, or can we compute it on the fly as `up - down`? It's better to avoid duplicating information when we can.

> I think we can have single model of Content instead of having 3 models including Comment and CommentThread. We can skip Comment and CommentThread and save the data directly in Content model based on it's 2 types that can be comment or thread.

It would seem to me that Comment and CommentThread are two very different types of objects. Why do you think they should be just one type? 

> Hmmm, we can also remove LastReadTime table and adjust/manage a single field of last_read_time in ReadState model.

LastReadTime actually contains three different fields. Do you mean that we should duplicate these three fields in all models that use LastReadTime?

**Comment by salman299** [comment]
- I believe it would be more organized to keep Comments and Threads as separate models because they represent distinct entities, despite sharing some common fields. Since models allow inheritance, we can create a Contents model to encapsulate these common fields.
- Is it possible to have different content_type values for a single content entry? The tables related to location seem unclear to me.
- In the abuse flagger, we could add a "status" field, this will minimize the delete queries. The same applies to the subscription model, we could have the status fields there.
- I think the votes table will need modification. We could rename it to user_votes to track the status for each user and content. Entries could include (content_id, user_id, status). Then, we could calculate derived properties like up_count, down_count, and points at runtime. If this slows down the queries, we could add up_count and down_count to the content model.
- The anonymous field in Activity is also causing confusion.
- The comment_thread_id in the comment model will serve as the foreign key.

**Comment by taimoor-ahmed-1** [comment]
> * I think we can have single model of `Content` instead of having 3 models including `Comment` and `CommentThread`. We can skip `Comment` and `CommentThread` and save the data directly in `Content` model based on it's 2 types that can be `comment or thread`.
> * we can remove `Activity` model, i think. We wrote in our decisions doc that it's not being used. Do we have still usage for this model?
> * Hmmm, we can also remove `LastReadTime` table and adjust/manage a single field of `last_read_time` in `ReadState` model.
> * Do we have some usage for `Position` table in our current implementation? or We can adjust it's single field `position` if require, in some other model.
> 
After discussion, we kept Comment and CommentThread models separate with an abstract model Content.
I have removed the Activity model now since we aren't migrating it in v2.
We could keep a JSONField for `last_read_times` but the onus will be on developers to maintain and validate it in code.
Position table was added for `at_position_list` but since its not being used in v2, I have removed it now.

**Comment by taimoor-ahmed-1** [comment]
> 1. User.default_sort_key, Position.content_type, Edit.reason_code, etc. should be enums (I think).
> 2. Timestamp fields should instead be localized datetimes.
> 3. Do we need CommentThread._type? According to [the docs](https://github.com/edly-io/forum/blob/master/docs/references/v1_models.rst#commentthread) it should always be "CommentThread".
> 4. Do we need Comment.course_id, given that it's already present in CommentThread.course_id?
> 5. Rename Activity.happend_at to Activity.happened_at.
> 6. Do we really need to store Vote.point, or can we compute it on the fly as `up - down`? It's better to avoid duplicating information when we can.
> 
> > I think we can have single model of Content instead of having 3 models including Comment and CommentThread. We can skip Comment and CommentThread and save the data directly in Content model based on it's 2 types that can be comment or thread.
> 
> It would seem to me that Comment and CommentThread are two very different types of objects. Why do you think they should be just one type?
> 
> > Hmmm, we can also remove LastReadTime table and adjust/manage a single field of last_read_time in ReadState model.
> 
> LastReadTime actually contains three different fields. Do you mean that we should duplicate these three fields in all models that use LastReadTime?

deprecated at_position_list, set choices for edit_reason_codes.
Updated to datetime objects instead of timestamps for all relevant fields
We have removed _type field now since we have separate models for Comment and CommentThread
Moved course_id to Content model now.
We have removed Activity model in v2 as per decisions doc.
We will keep a property for point and count in votes. Removed from db.

**Comment by taimoor-ahmed-1** [comment]
> * I believe it would be more organized to keep Comments and Threads as separate models because they represent distinct entities, despite sharing some common fields. Since models allow inheritance, we can create a Contents model to encapsulate these common fields.
> * Is it possible to have different content_type values for a single content entry? The tables related to location seem unclear to me.
> * In the abuse flagger, we could add a "status" field, this will minimize the delete queries. The same applies to the subscription model, we could have the status fields there.
> * I think the votes table will need modification. We could rename it to user_votes to track the status for each user and content. Entries could include (content_id, user_id, status). Then, we could calculate derived properties like up_count, down_count, and points at runtime. If this slows down the queries, we could add up_count and down_count to the content model.
> * The anonymous field in Activity is also causing confusion.
> * The comment_thread_id in the comment model will serve as the foreign key.

Kept the models separate with abstract class Content containing common fields.
We have removed the content_type field because we have separate models now.
Using "soft" deletes can be useful but will have to write additional queries to filter flaggers (prone to bugs). Plus, this table will grow too large if we don't delete records.
Added user field in votes and we will be deriving values at runtime. 
Activity model has been removed
Added foreign key for comment_thread_id in Comment table

**Comment by taimoor-ahmed-1** [comment]
Here is the updated ERD and the [models implementation in Django](https://github.com/edly-io/forum/blob/8280a00a838c373c0b427a0f41cfeba768091ebe/forum/backends/mysql/models.py), this is open for suggestions.
![forum_v2 (1)](https://github.com/user-attachments/assets/29636e92-e8b7-449e-8fbe-76e440c13254)

**Comment by salman299** [comment]
- For the Models part, we must have to store ObjectID somewhere. 
- In the UserVote model, we can add a unique constraint for (user, content). Similarly, we can add a unique constraint on subtraction, read_states

Also, mentioned these in the PR.
https://github.com/edly-io/forum/pull/89/files

**Comment by taimoor-ahmed-1** [comment]
The DBML from dbdiagram and final ERD
```
Table ForumUser {
  id integer [primary key]
  default_sort_key varchar
}

Table Content {
  id integer [primary key]
  visible bool
  author integer 
  course_id varchar
  body text
  endorsed bool
  anonymous bool
  group_id integer
  anonymous_to_peers bool
  commentable_id varchar
}

Table AbuseFlagger {
  content_id integer
  user_id integer
  flagged_at datetime
}

Table HistoricalAbuseFlagger {
  content_id integer
  user_id integer
  flagged_at datetime
}

Table CommentThread {
  id integer [unique, not null]
  thread_type varchar
  context varchar
  comment_count integer
  title varchar
  created_at datetime
  updated_at datetime
  last_activity_at datetime
  pinned bool
  closed bool
  closed_by int
  close_reason_code varchar
}

Table Comment {
  id integer [unique, not null]
  comment_thread_id integer
  endorsed bool
  child_count integer
  depth integer
  endorsement_user_id integer
  sort_key varchar
}

Table EditHistory {
  comment_id integer
  original_body text
  editing_user_id integer
  edit_reason_code varchar
}

Table UserVote {
  user integer [not null]
  content_id integer [unique, not null]
  vote integer
}

Table Subscription {
  source_id integer
  subscriber_id integer
}

Table CourseStat {
  user_id integer
  active_flags integer
  inactive_flags integer
  threads integer
  responses integer
  replies integer
  course_id varchar
  last_activity_at datetime
}

Table ReadState {
  id integer [primary key]
  user_id integer
  course_id varchar
}

Table LastReadTime {
  read_state_id integer
  content_id integer
  read_time datetime
}

Ref: LastReadTime.read_state_id > ReadState.id
Ref: LastReadTime.content_id > Content.id

Ref: ReadState.user_id > ForumUser.id

Ref: CourseStat.user_id > ForumUser.id

Ref: Subscription.source_id > Content.id
Ref: Subscription.subscriber_id > ForumUser.id

Ref: UserVote.content_id - Content.id

Ref: CommentThread.id - Content.id

Ref: Comment.id - Content.id

Ref: Content.author > ForumUser.id

Ref: AbuseFlagger.content_id > Content.id
Ref: AbuseFlagger.user_id > ForumUser.id

Ref: HistoricalAbuseFlagger.content_id > Content.id
Ref: HistoricalAbuseFlagger.user_id > ForumUser.id

Ref: Comment.comment_thread_id > CommentThread.id
Ref: UserVote.user > ForumUser.id

Ref: EditHistory.comment_id > Content.id
Ref: EditHistory.editing_user_id > ForumUser.id
```

![Image](https://github.com/user-attachments/assets/9d6524cd-27d3-473b-8e07-13038b086bb8)
